name: Release
on: 
  push:
    branches:
      - main

permissions: write-all

jobs:
  run:
    if: ${{ github.ref_name == 'main' || github.ref_name == 'develop'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install Volta
        uses: volta-cli/action@v4
      - name: Echo versions
        run: |
          node --version
          pnpm --version
      - name: Install dependencies
        run: pnpm install
        env:
          HUSKY: 0
      - name: Run tests
        run: pnpm run test
      - name: Build app
        run: pnpm run build:ts
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
