name: Test
on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install Volta
        uses: volta-cli/action@v4
      - name: Install dependencies
        run: pnpm install
        env:
          HUSKY: 0
      - name: Run tests
        run: pnpm run test
