name: Test
on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install -g pnpm  
      - name: Install dependencies
        run: pnpm install
        env:
          HUSKY: 0
      - name: Run tests
        run: pnpm run test
